import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { styleText } from "util";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/pretendard@1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.css"
        />
      </head>
      <body className="antialiased bg-gray-300 min-h-screen">
        <header className="pt-10 text-center text-4xl font-bold">
          <Link href={`/`}>백(BACK) 다방</Link>
        </header>

        <main className="mx-auto max-w-6xl px-6 py-8">
          <div className="bg-white rounded-2xl shadow-xl/30 p-5 max-h-[calc(100vh-180px)] overflow-y-auto">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
