import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { styleText } from "util";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className="h-screen overflow-hidden">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/pretendard@1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.css"
        />
      </head>
      <body className="antialiased bg-gray-300 h-screen overflow-hidden flex flex-col">
        <header className="pt-10 pb-6 text-center text-4xl font-bold">
          <Link href={`/`}>백(BACK) 다방</Link>
        </header>

        <main className="mx-auto max-w-6xl px-6 pb-8 flex-1 w-full overflow-hidden">
          <div className="bg-white rounded-2xl shadow-xl/30 overflow-hidden h-full flex">
            <div className="overflow-y-auto p-5 flex-1">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
